version: '3.5'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
    environment:
      - cluster.name=docker-elk
      - bootstrap.memory_lock=true
      - network.host=0.0.0.0
      - ES_JAVA_OPTS=-Xms2g -Xmx2g #xms minimum heap size, xmx maximum heap size
      - discovery.type=single-node  #to bypass bootstrap check on dev 
    ulimits: #not supported in stack how??? check log messages for a possible fix
      memlock:
        soft: -1
        hard: -1
    deploy:
      restart_policy:
        condition: any
        delay: 3s
        window: 10s
    #  temporary disabled
    #  placement:
    #    constraints:
    #      - node.labels.elastic == true # to mark nodes where vm.max_map_count=262144
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
      - target: 9300
        published: 9300
    networks:
      - elastic

  logstash:
    image: erdalkiran/logstash-oss:6.2.3
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 3s
        max_attempts: 10
        window: 10s
    ports:
      - published: 12201
        target: 12201
        protocol: udp
    depends_on: 
      - elasticsearch
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.3
    environment:
      - SERVER_HOST=0.0.0.0
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    deploy:
      restart_policy:
        condition: any
        delay: 3s
        window: 10s
    ports:
      - target: 5601
        published: 5601
    depends_on: 
      - elasticsearch
    networks:
      - elastic

  filebeat-demo:
    image: erdalkiran/filebeat
    deploy:
      restart_policy:
        condition: any
        delay: 3s
        max_attempts: 10
        window: 10s
    depends_on: 
      - logstash
    networks:
      - elastic
  
  nginx:
    image: nginx:1.13.12-alpine
    deploy:
      restart_policy:
        condition: any
        delay: 3s
        max_attempts: 10
        window: 10s
    ports:
      - published: 80
        target: 80
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "nginx"
    depends_on: 
      - logstash
    networks:
      - elastic

volumes:
  esdata:

networks: 
  elastic:

    