version: '3.5'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
    environment:
      - cluster.name=docker-elk
      - bootstrap.memory_lock=true
      - network.host=0.0.0.0
      - ES_JAVA_OPTS=-Xms2g -Xmx2g #xms minimum heap size, xmx maximum heap size
      - discovery.type=single-node  #to bypass bootstrap check on dev 
    ulimits: #not supported in stack how??? check log messages for a possible fix
      memlock:
        soft: -1
        hard: -1
    #temporary disabled
    #deploy:
    #  placement:
    #    constraints:
    #      - node.labels.elastic == true # to mark nodes where vm.max_map_count=262144
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
      - target: 9300
        published: 9300
    networks:
      - elastic
      
  logstash:
    image: erdalkiran/logstash-oss:6.2.3
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.3
    environment:
      - SERVER_HOST=0.0.0.0
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - target: 5601
        published: 5601
    networks:
      - elastic

volumes:
  esdata:

networks: 
  elastic:

    